detect if second user is typing
Gregi96/react-firebase-v2 pull request #2
Opened 2022-07-07 13:59 UTC by Gregi96

2022-07-07 14:06 UTC, gtarnopolski requested changes

2022-07-07 14:14 UTC, gtarnopolski requested changes

2022-07-07 15:33 UTC, gtarnopolski approved these changes

2022-07-07 15:52 UTC, jpudysz requested changes

2022-07-07 16:11 UTC, jpudysz requested changes
Ok, until then I will keep it blocked

2022-07-08 08:59 UTC, jpudysz requested changes

2022-07-08 08:59 UTC, jpudysz commented on src/lib/hooks/useUserMessages.ts
> +        const messageRef = collection(db, 'generalMessages')
to enum

2022-07-08 08:59 UTC, jpudysz commented on src/components/Home.tsx
> +    useEffect(() => {
you have a lot of logic here, extracting it to hook or utils would be nice :)

2022-07-08 09:38 UTC, GrzegorzTarnopolski approved these changes

2022-07-20 11:49 UTC, merged